name: Build Android APK - Fast

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Android and Build
      uses: android-actions/build-android@v1
      with:
        build-task: assembleDebug
        build-root-directory: ./
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MediaReceiverPro-APK
        path: app/build/outputs/apk/debug/app-debug.apk
